services:
  sqlite:
    build: .
    volumes:
      - ./app:/app
      - ./data:/data
      - ./scripts:/scripts

    ports:
        - "8080:8080"
    container_name: sqlite_db
    environment:
      - PYTHONUNBUFFERED=1 # Real-time logs