services:
  sqlite:
    build: .
    volumes:
      - ./app:/app
      - ./data:/data
      - ./scripts:/scripts

    ports:
      - "8090:8080"
    #container_name: sqlite_db
    environment:
      - PYTHONUNBUFFERED=1 # Real-time logs

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.ci # Custom Dockerfile for Jenkins
    image: jenkins-ci:latest
    user: root
    ports:
      - "8091:8080" # Jenkins UI
      - "50000:50000" # Jenkins agent
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app # Mount code for builds
    #container_name: jenkins